#!/bin/ash

set -o errexit
set -o pipefail
set -o nounset


if [ -z "${DATABASE__USER}" ]; then
    base_postgres_image_default_user='postgres'
    export DATABASE__USER="${base_postgres_image_default_user}"
fi
export DATABASE__URL="${DATABASE__PROTOCOL}://${DATABASE__USER}:${DATABASE__PASSWORD}@${DATABASE__HOST}:${DATABASE__PORT}/${DATABASE__DATABASE}"


postgres_ready() {
python << END

import sys
import psycopg2

try:
    psycopg2.connect(
        dbname="${DATABASE__DATABASE}",
        user="${DATABASE__USER}",
        password="${DATABASE__PASSWORD}",
        host="${DATABASE__HOST}",
        port="${DATABASE__PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
