#!/bin/ash

set -o errexit
set -o pipefail
set -o nounset

export PATH=$PATH:/home/$(whoami)/.local/bin

if [ -z "${DATABASE__USERNAME}" ]; then
    base_postgres_image_default_user='postgres'
    export DATABASE__USERNAME="${base_postgres_image_default_user}"
fi
export DATABASE__URL="${DATABASE__PROTOCOL}://${DATABASE__USERNAME}:${DATABASE__PASSWORD}@${DATABASE__HOSTNAME}:${DATABASE__PORT}/${DATABASE__DATABASE}"


postgres_ready() {
python << END

import sys
import asyncio
import asyncpg

async def main():
    try:
        conn = await asyncpg.connect(
            host="${DATABASE__HOSTNAME}",
            port="${DATABASE__PORT}",
            database="${DATABASE__DATABASE}",
            user="${DATABASE__USERNAME}",
            password="${DATABASE__PASSWORD}",
        )
        await conn.close()
    except:
        sys.exit(-1)

asyncio.get_event_loop().run_until_complete(main())

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
